#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='dash'
git_name='dash-debian'
version='0.5.12'
gittag="v${version}"
source_archive() {
	extension='.orig.tar.gz'
	url='http://deb.debian.org/debian/pool/main/d/'"${name}"'/'"${name}"'_'"${version}${extension}"
	SHA256='6a474ac46e8b0b32916c4c60df694c82058d3297d8b385b74508030ca4a8f28a'
	SIZE='x'
}
buildtools="asciidoc xgettext"

fetch_or_checkout_source

export CDPATH=

uses_gnu_autotools
uses_gnu_make
check_buildtools
clone_source_to_build

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
(
	cd build
	auto_reconfigure
	test -r config.status || sh ./configure --with-libedit --enable-glob --enable-fnmatch
	"${make}" ${cpus:+ -j "${cpus}"}
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual

# ##############################################################################
# Build all of the ...{new} files in ./command and ./manual.
for section in 1 2 3 4 5 6 7 8 9
do
	# All of the commands that have executables
	test -r package/commands${section} && cat package/commands${section} |
	while read -r i
	do
		rm -f -- command/"$i"{new}
		if objdump -f build/src/"$i" >/dev/null 2>&1
		then
			install -m 0755 -p -- build/src/"$i" command/"$i"{new}
			strip -p -- command/"$i"{new}
			chmod 0555 command/"$i"{new}
		else
			install -m 0555 -p -- build/src/"$i" command/"$i"{new}
		fi
	done
	# All of the commands that have their own manual pages
	test -r package/commands${section} && cat package/commands${section} |
	while read -r i
	do
		install -d -m 0755 -- manual/man${section}
		rm -f -- manual/man${section}/"$i".${section}{new}
		install -m 0444 -p -- build/src/"$i".${section} manual/man${section}/"$i".${section}{new}
	done
	test -r package/extra-manpages${section} && cat package/extra-manpages${section} |
	while read -r i
	do
		install -d -m 0755 -- manual/man${section}
		rm -f -- manual/man${section}/"$i".${section}{new}
		install -m 0444 -p -- build/src/bltin/"$i".${section} manual/man${section}/"$i".${section}{new}
	done
done
collapse_utf8_man_0

# ##############################################################################
# Rename the ...{new} files in ./command and ./manual.
for section in 1 2 3 4 5 6 7 8 9
do
	# All of the commands that have executables
	test -r package/commands${section} && cat package/commands${section} |
	while read -r i
	do
		mv -f -- command/"$i"{new} command/"$i"
	done
	# All of the commands that have their own manual pages
	test -r package/commands${section} && cat package/commands${section} |
	while read -r i
	do
		mv -f -- manual/man${section}/"$i".${section}{new} manual/man${section}/"$i".${section}
	done
	test -r package/extra-manpages${section} && cat package/extra-manpages${section} |
	while read -r i
	do
		mv -f -- manual/man${section}/"$i".${section}{new} manual/man${section}/"$i".${section}
	done
done
collapse_utf8_man_1
