#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='dash'
git_name='dash-debian'
version='0.5.12'
gittag="v${version}"
source_archive() {
	extension='.orig.tar.gz'
	url='http://deb.debian.org/debian/pool/main/d/'"${name}"'/'"${name}"'_'"${version}${extension}"
	SHA256='6a474ac46e8b0b32916c4c60df694c82058d3297d8b385b74508030ca4a8f28a'
	SIZE='x'
}
buildtools="asciidoc xgettext"

fetch_or_checkout_source

export CDPATH=

uses_gnu_autotools
uses_gnu_make
check_buildtools
clone_source_to_build

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
(
	cd build
	auto_reconfigure
	test -r config.status || sh ./configure --with-libedit --enable-glob --enable-fnmatch
	"${make}" ${cpus:+ -j "${cpus}"}
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual

# ##############################################################################
# Build all of the ...{new} files in ./command and ./manual.
install_commands_0 src
install_manuals_0 src ''
collapse_utf8_man_0

# ##############################################################################
# Rename the ...{new} files in ./command and ./manual.
install_commands_1
install_manuals_1 ''
collapse_utf8_man_1
