#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='xmlto'
version='0.0.29'
source_archive() {
	extension='.tar.gz'
	url='http://releases.pagure.org/'"${name}"'/'"${name}"'-'"${version}${extension}"
	SHA256='x'
	SIZE='x'
}
buildtools=

fetch_or_checkout_source

export CDPATH=

uses_gnu_autotools_sans_autoreconf
uses_gnu_make
check_buildtools
clone_source_to_build

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
target="${PWD}"
(
	cd build
	automake_options="--foreign"
	auto_reconfigure
	test -r config.status || XMLTO_BASH_PATH="$(command -v sh)" sh ./configure --datarootdir="${target}"/config --with-webbrowser=www-browser
	"${make}" ${cpus:+ -j "${cpus}"}
)

# Atomically update the release directories ./command, ./config, ./manual, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual config

# ##############################################################################
# Build all of the ...{new} files in ./command and ./manual.
for section in 1 2 3 4 5 6 7 8 9
do
	# All of the commands that have executables
	test -r package/commands${section} && cat package/commands${section} |
	while read -r i
	do
		rm -f -- command/"$i"{new}
		if objdump -f build/"$i"/"$i" >/dev/null 2>&1
		then
			install -m 0755 -p -- build/"$i"/"$i" command/"$i"{new}
			strip -p -- command/"$i"{new}
			chmod 0555 command/"$i"{new}
		elif test -f build/"$i"
		then
			install -m 0555 -p -- build/"$i" command/"$i"{new}
		fi
	done
	# All of the commands that have their own manual pages
	test -r package/commands${section} && cat package/commands${section} |
	while read -r i
	do
		install -d -m 0755 -- manual/man${section} manual/docbook${section}
		rm -f -- manual/man${section}/"$i".${section}{new} manual/docbook${section}/"$i".xml{new}
		install -m 0444 -p -- build/man/man${section}/"$i".${section} manual/man${section}/"$i".${section}{new}
		install -m 0444 -p -- build/doc/"$i".xml manual/docbook${section}/"$i".xml{new}
	done
	test -r package/extra-manpages${section} && cat package/extra-manpages${section} |
	while read -r i
	do
		install -d -m 0755 -- manual/man${section} manual/docbook${section}
		rm -f -- manual/man${section}/"$i".${section}{new} manual/docbook${section}/"$i".xml{new}
		install -m 0444 -p -- build/man/man${section}/"$i".${section} manual/man${section}/"$i".${section}{new}
		install -m 0444 -p -- build/doc/"$i".xml manual/docbook${section}/"$i".xml{new}
	done
done
collapse_utf8_man_0
# format and make files
for directory in format
do
	install -d -m 0755 config/"${directory}"{new}
	(
		cd build/"${directory}"
		pax -r -w -p a * ../../config/"${directory}"{new}
	)
	find config/"${directory}"{new}/ -name '*.orig' -delete
done
for file in xmlto.mak
do
	rm -f -- config/"${file}"{new}
	install -m 0444 -p -- build/"${file}" config/"${file}"{new}
done
for link in xmlto
do
	make_symbolic_link . config/"${link}"{new}
done

# ##############################################################################
# Rename the ...{new} files in ./command and ./manual.
for section in 1 2 3 4 5 6 7 8 9
do
	# All of the commands that have executables
	test -r package/commands${section} && cat package/commands${section} |
	while read -r i
	do
		mv -f -- command/"$i"{new} command/"$i"
	done
	# All of the commands that have their own manual pages
	test -r package/commands${section} && cat package/commands${section} |
	while read -r i
	do
		mv -f -- manual/man${section}/"$i".${section}{new} manual/man${section}/"$i".${section}
		mv -f -- manual/docbook${section}/"$i".xml{new} manual/docbook${section}/"$i".xml
	done
	test -r package/extra-manpages${section} && cat package/extra-manpages${section} |
	while read -r i
	do
		mv -f -- manual/man${section}/"$i".${section}{new} manual/man${section}/"$i".${section}
		mv -f -- manual/docbook${section}/"$i".xml{new} manual/docbook${section}/"$i".xml
	done
done
collapse_utf8_man_1
# format and make files
for directory in format
do
	rename_directory config/"${directory}"{new} config/"${directory}"
done
for file in xmlto.mak
do
	mv -f -- config/"${file}"{new} config/"${file}"
done
for link in xmlto
do
	rename_symbolic_link config/"${link}"{new} config/"${link}"
done
