#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='zhcon'
version='0.2.3'
source_archive() {
	extension='.tar.gz'
	url='http://downloads.sourceforge.net/project/'"${name}/${name}/${version}/${name}-${version}${extension}"
	SHA256='60e2f7a3b2a548e043838794b7ab3cb0e84f13508d48b384e9b6598698baacbb'
	SIZE='5030677'
}
buildtools=

fetch_or_checkout_source

export CDPATH=

clone_source_to_build

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
(
	cd build
	test -r config.status || sh ./configure --disable-nls
	make ${cpus:+ -j "${cpus}"} -k
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual config config/locale config/share config/share/font

# ##############################################################################
# Build all of the ...{new} files in ./command and ./manual.
install_commands_0 src
install_manuals_0 doc ''
collapse_utf8_man_0

# ##############################################################################
# Rename the ...{new} files in ./command and ./manual.
install_commands_1
install_manuals_1 ''
collapse_utf8_man_1

# ##############################################################################
# Build all of the ...{new} files in ./config.
find build/po -name '*.mo' |
while read -r mo
do
	i="`basename \"${mo}\" .mo`"
	install -d -m 0755 -- config/locale/"$i"/LC_MESSAGES
	rm -f -- config/locale/"$i"/LC_MESSAGES/yash.mo{new}
	install -m 0444 -p -- "${mo}" config/locale/"$i"/LC_MESSAGES/yash.mo{new}
done
find build/font -name '*.bpsf' |
while read -r font
do
	i="`basename \"${font}\"`"
	rm -f -- config/share/font/"$i"{new}
	install -m 0444 -p -- "${font}" config/share/font/"$i"{new}
done

# ##############################################################################
# Rename the ...{new} directories and files in ./config.
find build/po -name '*.mo' |
while read -r mo
do
	i="`basename \"${mo}\" .mo`"
	mv -f -- config/locale/"$i"/LC_MESSAGES/yash.mo{new} config/locale/"$i"/LC_MESSAGES/yash.mo
done
find build/font -name '*.bpsf' |
while read -r font
do
	i="`basename \"${font}\"`"
	mv -f -- config/share/font/"$i"{new} config/share/font/"$i"
done
