#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='unifont'
version='17.0.05'
source_archive() {
	extension='.tar.gz'
	url='http://ftpmirror.gnu.org'/"${name}"/"${name}-${version}"/"${name}-${version}${extension}"
	SHA256='f287cffb26e22723aa36e6684869b0f3ff3bfb822c4b01008bd847911ec1b631'
	SIZE='41506878'
}
buildtools=vtfontcvt

fetch_or_checkout_source

export CDPATH=

clone_source_to_build

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
(
	cd build
	make ${cpus:+ -j "${cpus}"} BUILDFONT= PERL=perl
)
(
	test -r package/fonts && cat package/fonts
) |
while read -r font
do
	vtfontcvt build/font/precompiled/"${font}".hex build/font/precompiled/"${font}".fnt
done

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual config config/fonts

# ##############################################################################
# Build all of the ...{new} files in ./command and ./manual.
install_commands_0 bin
install_manuals_0 man ''
collapse_utf8_man_0

# ##############################################################################
# Rename the ...{new} files in ./command and ./manual.
install_commands_1
install_manuals_1 '' ''
collapse_utf8_man_1

# ##############################################################################
# Build all of the ...{new} files in ./config.
install_fonts_0 font/precompiled .fnt

# ##############################################################################
# Rename the ...{new} directories and files in ./config.
install_fonts_1 .fnt
