#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='unscii'
version='2.1'
suffix='-src'
gittag='main'
source_archive() {
	extension='.tar.gz'
	url='http://viznut.fi'/"${name}"/"${name}-${version}${suffix}${extension}"
	SHA256='4d1215d495e49d005ae70828ec1529e997049b9a7f152b9439d78c7e70c65b57'
	SIZE='1277989'
}
buildtools="vtfontcvt"

apply_local_changes() {
	install -d -m 0755 source/fontfiles
}
cleanup_source_from_git() {
	rm -f -- source/fontfiles/unscii-*
}

fetch_or_checkout_source

export CDPATH=

clone_source_to_build

check_buildtools

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
(
	cd build
	make ${cpus:+ -j "${cpus}"} fnt bdf
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 config/fonts

# ##############################################################################
# Build all of the ...{new} files in ./config.
install_fonts_0 fontfiles .fnt .bdf

# ##############################################################################
# Rename the ...{new} directories and files in ./config.
install_fonts_1 .fnt .bdf
