#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='dash'
git_name='dash-xu'
version='0.5.13.5'
gittag="v${version}"
source_archive() {
	extension='.tar.gz'
	url='https://git.kernel.org/pub/scm/utils/'"${name}"'/'"${name}"'.git/snapshot/'"${name}"'-'"${version}${extension}"
	SHA256='x'
	SIZE='x'
}
buildtools="asciidoc xgettext"

fetch_or_checkout_source

export CDPATH=

uses_gnu_autotools
uses_gnu_make
check_buildtools
clone_source_to_build

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
(
	cd build
	auto_reconfigure
	export CPPFLAGS='-U DEBUG'
	test -r config.status || sh ./configure --with-libedit --enable-glob --enable-fnmatch
	"${make}" ${cpus:+ -j "${cpus}"}
	for i in dash
	do
		ln -f -- src/"$i".1 src/bltin/
	done
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual

# ##############################################################################
# Build all of the ...{new} files in ./command and ./manual.
install_commands_0 src
install_manuals_0 src/bltin ''
collapse_utf8_man_0

# ##############################################################################
# Rename the ...{new} files in ./command and ./manual.
install_commands_1
install_manuals_1 '' ''
collapse_utf8_man_1
