#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='freedt'
version='23'
gittag="v${version}"
source_archive() {
	extension='.tar.gz'
	url='http://offog.org/files/'/"${name}-${version}${extension}"
	SHA256='b0176d6f3c290f3d281804b61906b91f332801109ec8c991689c4113a028e42c'
	SIZE='106539'
}
buildtools=

fetch_or_checkout_source

export CDPATH=

uses_gnu_autotools
check_buildtools
clone_source_to_build

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
(
	cd build
	auto_reconfigure
	test -r config.status || sh ./configure
	make ${cpus:+ -j "${cpus}"}
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual

# ##############################################################################
# Build all of the ...{new} files in ./command and ./manual.
for section in 1 2 3 4 5 6 7 8 9
do
	# All of the commands that have executables
	test -r package/commands${section} && cat package/commands${section} |
	while read -r i
	do
		rm -f -- command/"$i"{new}
		if objdump -f build/"$i" >/dev/null 2>&1
		then
			install -m 0755 -p -- build/"$i" command/"$i"{new}
			strip -p -- command/"$i"{new}
			chmod 0555 command/"$i"{new}
		else
			install -m 0555 -p -- build/"$i" command/"$i"{new}
		fi
	done
	# All of the aliases for other commands
	test -r package/aliases${section} && cat package/aliases${section} |
	while read -r command alias
	do
		rm -f -- command/"${alias}"{new}
		ln -f -- command/"${command}"{new} command/"${alias}"{new}
	done
	# All of the commands that have their own manual pages
	(
#		test -r package/commands${section} && cat package/commands${section}
		test -r package/extra-manpages${section} && cat package/extra-manpages${section}
	) |
	while read -r i
	do
		install -d -m 0755 -- manual/man${section} manual/ja/man${section}
		rm -f -- manual/man${section}/"$i".${section}{new}
		install -m 0444 -p -- build/doc/"$i".${section} manual/man${section}/"$i".${section}{new}
		install -m 0444 -p -- build/doc/ja/"$i".${section} manual/ja/man${section}/"$i".${section}{new}
	done
	# All of the manual pages for aliases
	(
#		test -r package/aliases${section} && cat package/aliases${section}
	) |
	while read -r command alias
	do
		test -r package/commands${section} && grep -q -- "^${alias}\$" package/commands${section} && continue
		test -r package/extra-manpages${section} && grep -q -- "^${alias}\$" package/extra-manpages${section} && continue
		ln -f -s -- "${command}".${section} manual/man${section}/"${alias}".${section}{new}
		ln -f -s -- "${command}".${section} manual/ja/man${section}/"${alias}".${section}{new}
	done
done
collapse_utf8_man_0

# ##############################################################################
# Rename the ...{new} files in ./command and ./manual.
for section in 1 2 3 4 5 6 7 8 9
do
	# All of the commands that have executables and all of their aliases
	(
		test -r package/commands${section} && cat package/commands${section}
		test -r package/aliases${section} && awk '{print $2;}' package/aliases${section}
	) |
	while read -r i
	do
		mv -f -- command/"$i"{new} command/"$i"
	done
	# All of the commands that have their own manual pages
	(
#		test -r package/commands${section} && cat package/commands${section}
		test -r package/extra-manpages${section} && cat package/extra-manpages${section}
	) |
	while read -r i
	do
		mv -f -- manual/man${section}/"$i".${section}{new} manual/man${section}/"$i".${section}
		mv -f -- manual/ja/man${section}/"$i".${section}{new} manual/ja/man${section}/"$i".${section}
	done
	# All of the manual pages for aliases
	(
#		test -r package/aliases${section} && cat package/aliases${section}
	) |
	while read -r command alias
	do
		test -r package/commands${section} && grep -q -- "^${alias}\$" package/commands${section} && continue
		test -r package/extra-manpages${section} && grep -q -- "^${alias}\$" package/extra-manpages${section} && continue
		mv -f -- manual/man${section}/"${alias}".${section}{new} manual/man${section}/"${alias}".${section}
		mv -f -- manual/ja/man${section}/"${alias}".${section}{new} manual/ja/man${section}/"${alias}".${section}
	done
done
collapse_utf8_man_1

# ##############################################################################
# Build all of the ...{new} files in ./config.

# ##############################################################################
# Rename the ...{new} directories and files in ./config.
