#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='freedt'
version='23'
gittag="v${version}"
source_archive() {
	extension='.tar.gz'
	url='http://offog.org/files/'/"${name}-${version}${extension}"
	SHA256='b0176d6f3c290f3d281804b61906b91f332801109ec8c991689c4113a028e42c'
	SIZE='106539'
}
buildtools=

fetch_or_checkout_source

export CDPATH=

uses_gnu_autotools
check_buildtools
clone_source_to_build

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
(
	cd build
	auto_reconfigure
	test -r config.status || sh ./configure
	make ${cpus:+ -j "${cpus}"}
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual

# ##############################################################################
# Build all of the ...{new} files in ./command and ./manual.
install_commands_0 .
install_manuals_0 . ''
collapse_utf8_man_0

# ##############################################################################
# Rename the ...{new} files in ./command and ./manual.
install_commands_1
install_manuals_1 ''
collapse_utf8_man_1
