#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='sash'
version='3.8'
gittag="v${version}"
source_archive() {
	extension='.tar.gz'
	url='http://members.tip.net.au/%7Edbell/programs/'"${name}"'-'"${version}${extension}"
	SHA256='13c4f9a911526949096bf543c21a41149e6b037061193b15ba6b707eea7b6579'
	SIZE='53049'
}
buildtools=

apply_local_changes() {
	case "`uname`" in
	Linux)	;;
	*)	printf '%s\n' '%s/\(HAVE_LINUX_[[:alnum:]_]*[[:space:]]*\)= 1/\1= 0/' '%s/\(MOUNT_TYPE[[:space:]]*\)= '"'"'"ext3"'"'"'/\1= '"'"'"ufs"'"'"'/' 'wq' | ex source/Makefile ;;
	esac
}

fetch_or_checkout_source

export CDPATH=

uses_gnu_make
check_buildtools
clone_source_to_build

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
(
	cd build
	"${make}" ${cpus:+ -j "${cpus}"}
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual

# ##############################################################################
# Build all of the ...{new} files in ./command and ./manual.
install_commands_0 .
install_manuals_0 . ''
collapse_utf8_man_0

# ##############################################################################
# Rename the ...{new} files in ./command and ./manual.
install_commands_1
install_manuals_1 '' ''
collapse_utf8_man_1
