#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='jfbterm'
version='0.6.1'
gittag='master'
source_archive() {
	extension='.tar.gz'
	url='http://downloads.sourceforge.net/project/'"${name}/${name}/${version}/${name}-${version}${extension}"
	SHA256='-1'
	SIZE='-1'
}
buildtools=

apply_local_changes() {
	rm -f -- source/configure source/config.status
}

fetch_or_checkout_source

export CDPATH=

uses_gnu_autotools
uses_bsd_make
check_buildtools
clone_source_to_build

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
(
	cd build
	auto_reconfigure
	test -r config.status || sh ./configure CPPFLAGS=-I/usr/local/include CFLAGS=-DLIBICONV_PLUG LDFLAGS=-L/usr/local/lib LIBS-liconv --prefix=/usr/local --mandir=/usr/local/man
	"${make}" ${cpus:+ -j "${cpus}"}
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual config config/share config/share/fonts

# ##############################################################################
# Build all of the ...{new} files in ./command and ./manual.
install_commands_0 .
install_manuals_0 . ''
collapse_utf8_man_0

# ##############################################################################
# Rename the ...{new} files in ./command and ./manual.
install_commands_1
install_manuals_1 ''
collapse_utf8_man_1

# ##############################################################################
# Build all of the ...{new} files in ./config.
find build/fonts -name '*.pcf.gz' |
while read -r font
do
	i="`basename \"${font}\"`"
	rm -f -- config/share/fonts/"$i"{new}
	install -m 0444 -p -- "${font}" config/share/fonts/"$i"{new}
done
echo jfbterm.conf.sample."`uname -s`" |
while read -r file
do
	i="`basename \"${file}\"`"
	rm -f -- config/"$i"{new}
	install -m 0444 -p -- build/"${file}" config/"$i"{new}
done

# ##############################################################################
# Rename the ...{new} directories and files in ./config.
find build/fonts -name '*.pcf.gz' |
while read -r font
do
	i="`basename \"${font}\"`"
	mv -f -- config/share/fonts/"$i"{new} config/share/fonts/"$i"
done
echo jfbterm.conf.sample."`uname -s`" |
while read -r file
do
	i="`basename \"${file}\"`"
	mv -f -- config/"$i"{new} config/"$i"
done
