#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='yash'
version='2.54'
gittag="${version}"
source_archive() {
	extension='.tar.xz'
	url='https://github.com/magicant/yash/releases/download/'"${version}"/"${name}-${version}${extension}"
	SHA256='44a0ac1ccf7c3acecfbea027d8c0c930f13a828065be318055ce113015391839'
	SIZE='758916'
}
buildtools="asciidoc xgettext"

cleanup_dist_from_archive() {
	# Cleanup bogus stuff in the source archive.
	find dist/"${name}-${version}"/ -name \*.d -delete
	find dist/"${name}-${version}"/doc/ -name \*.html -delete
	find dist/"${name}-${version}"/po/ -name \*.mo -delete
	rm -f dist/"${name}-${version}"/po/en@boldquot.ih
	rm -f dist/"${name}-${version}"/po/en@boldquot.po
	rm -f dist/"${name}-${version}"/po/en@quot.ih
	rm -f dist/"${name}-${version}"/po/en@quot.po
	rm -f dist/"${name}-${version}"/po/yash.pot
	rm -f dist/"${name}-${version}"/po/stamp-po
	rm -f dist/"${name}-${version}"/doc/yash.1
	rm -f dist/"${name}-${version}"/doc/yash.txt
	rm -f dist/"${name}-${version}"/doc/index.txt
	rm -f dist/"${name}-${version}"/doc/ja/yash.1
	rm -f dist/"${name}-${version}"/doc/ja/yash.txt
	rm -f dist/"${name}-${version}"/doc/ja/index.txt
}

fetch_or_checkout_source

export CDPATH=

check_buildtools
clone_source_to_build

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
(
	cd build
	test -r config.status || sh ./configure --disable-nls
	make ${cpus:+ -j "${cpus}"}
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual guide config manual/ja guide/ja config/locale config/share

# ##############################################################################
# Build all of the ...{new} files in ./command and ./manual.
for section in 1 2 3 4 5 6 7 8 9
do
	# All of the commands that have executables
	test -r package/commands${section} && cat package/commands${section} |
	while read -r i
	do
		rm -f -- command/"$i"{new}
		if objdump -f build/"$i" >/dev/null 2>&1
		then
			install -m 0755 -p -- build/"$i" command/"$i"{new}
			strip -p -- command/"$i"{new}
			chmod 0555 command/"$i"{new}
		else
			install -m 0555 -p -- build/"$i" command/"$i"{new}
		fi
	done
	# All of the aliases for other commands
	test -r package/aliases${section} && cat package/aliases${section} |
	while read -r command alias
	do
		rm -f -- command/"${alias}"{new}
		ln -f -- command/"${command}"{new} command/"${alias}"{new}
	done
	# All of the commands that have their own manual pages
	(
		test -r package/commands${section} && cat package/commands${section}
		test -r package/extra-manpages${section} && cat package/extra-manpages${section}
	) |
	while read -r i
	do
		install -d -m 0755 -- manual/man${section} manual/ja/man${section}
		rm -f -- manual/man${section}/"$i".${section}{new}
		install -m 0444 -p -- build/doc/"$i".${section} manual/man${section}/"$i".${section}{new}
		install -m 0444 -p -- build/doc/ja/"$i".${section} manual/ja/man${section}/"$i".${section}{new}
	done
	# All of the manual pages for aliases
	test -r package/aliases${section} && cat package/aliases${section} |
	while read -r command alias
	do
		test -r package/commands${section} && grep -q -- "^${alias}\$" package/commands${section} && continue
		test -r package/extra-manpages${section} && grep -q -- "^${alias}\$" package/extra-manpages${section} && continue
		ln -f -s -- "${command}".${section} manual/man${section}/"${alias}".${section}{new}
		ln -f -s -- "${command}".${section} manual/ja/man${section}/"${alias}".${section}{new}
	done
done
# Main guide pages
cat package/guidepages |
while read -r i
do
	rm -f -- guide/"$i".html{new}
	rm -f -- guide/ja/"$i".html{new}
	install -m 0444 -p -- build/doc/"$i".html guide/"$i".html{new}
	install -m 0444 -p -- build/doc/ja/"$i".html guide/ja/"$i".html{new}
done
collapse_utf8_man_0

# ##############################################################################
# Rename the ...{new} files in ./command and ./manual.
for section in 1 2 3 4 5 6 7 8 9
do
	# All of the commands that have executables and all of their aliases
	(
		test -r package/commands${section} && cat package/commands${section}
		test -r package/aliases${section} && awk '{print $2;}' package/aliases${section}
	) |
	while read -r i
	do
		mv -f -- command/"$i"{new} command/"$i"
	done
	# All of the commands that have their own manual pages
	(
		test -r package/commands${section} && cat package/commands${section}
		test -r package/extra-manpages${section} && cat package/extra-manpages${section}
	) |
	while read -r i
	do
		mv -f -- manual/man${section}/"$i".${section}{new} manual/man${section}/"$i".${section}
		mv -f -- manual/ja/man${section}/"$i".${section}{new} manual/ja/man${section}/"$i".${section}
	done
	# All of the manual pages for aliases
	test -r package/aliases${section} && cat package/aliases${section} |
	while read -r command alias
	do
		test -r package/commands${section} && grep -q -- "^${alias}\$" package/commands${section} && continue
		test -r package/extra-manpages${section} && grep -q -- "^${alias}\$" package/extra-manpages${section} && continue
		mv -f -- manual/man${section}/"${alias}".${section}{new} manual/man${section}/"${alias}".${section}
		mv -f -- manual/ja/man${section}/"${alias}".${section}{new} manual/ja/man${section}/"${alias}".${section}
	done
done
# Main guide pages
cat package/guidepages |
while read -r i
do
	mv -f -- guide/"$i".html{new} guide/"$i".html
	mv -f -- guide/ja/"$i".html{new} guide/ja/"$i".html
done
collapse_utf8_man_1

# ##############################################################################
# Build all of the ...{new} files in ./config.
for mo in build/po/*.mo
do
	i="`basename \"${mo}\" .mo`"
	install -d -m 0755 -- config/locale/"$i"/LC_MESSAGES
	rm -f -- config/locale/"$i"/LC_MESSAGES/yash.mo{new}
	install -m 0444 -p -- "${mo}" config/locale/"$i"/LC_MESSAGES/yash.mo{new}
done
rm -r -f -- config/share{new}/
install -d -m 0755 config/share{new}
( cd build/share/ && pax -r -w * ../../config/share{new}/ )
mv -f -- config/share{new}/config config/share{new}/config.nonslashpackage
cwd="`/bin/pwd`"
sed \
	-e 's:/usr/local/bin:'${cwd}'/command:g' \
	-e 's:/usr/local/share/yash:'${cwd}'/config/share:g' \
	-e 's:/usr/local/share/man:'${cwd}'/manual:g' \
	-e 's:/usr/local/share/doc/yash:'${cwd}'/doc:g' \
	-e 's:/usr/local/share/locale:'${cwd}'/config/locale:g' \
	config/share{new}/config.nonslashpackage > config/share{new}/config

# ##############################################################################
# Rename the ...{new} directories and files in ./config.
for mo in build/po/*.mo
do
	i="`basename \"${mo}\" .mo`"
	mv -f -- config/locale/"$i"/LC_MESSAGES/yash.mo{new} config/locale/"$i"/LC_MESSAGES/yash.mo
done
test -e config/share && mv -f -- config/share config/share{old}
mv -f -- config/share{new} config/share
rm -r -f -- config/share{old}
