#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2 
	exit 100
fi

exec rm -rf build/ debian/ bsd/ command/ manual/ source/ dist/ config/
