#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='unscii'
version='2.1.1f'
suffix=''
gittag='2.1.1f'
source_archive() {
	extension='.tar.gz'
	url='http://viznut.fi'/"${name}"/"${name}-${version}${suffix}${extension}"
	SHA256='x'
	SIZE='x'
}
buildtools="vtfontcvt"

apply_local_changes() {
	install -d -m 0755 source/fontfiles
}

fetch_or_checkout_source

export CDPATH=

clone_source_to_build

check_buildtools

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
(
	cd build
	make ${cpus:+ -j "${cpus}"} fnt bdf
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 config/fonts

# ##############################################################################
# Build all of the ...{new} files in ./config.
(
	test -r package/fonts && cat package/fonts
) |
while read -r font
do
	rm -f -- config/fonts/"${font}"{new}
	install -m 0444 -p -- build/fontfiles/"${font}" config/fonts/"${font}"{new}
done

# ##############################################################################
# Rename the ...{new} directories and files in ./config.
(
	test -r package/fonts && cat package/fonts
) |
while read -r font
do
	mv -f -- config/fonts/"${font}"{new} config/fonts/"${font}"
done
