#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='paxmirabilis'
git_name="${name}"
version='20201030'
gittag="${version}"
source_archive() {
	extension='.cpio.gz'
	url='http://mbsd.evolvis.org/MirOS/dist/mir/cpio/'"${name}"'-'"${version}${extension}"
	dirname=pax
	SHA256='fe3f99c28ba7a46c4bce0b329da3742908b87fe8fbe17f0db1f99a1bd053d46b'
	SIZE='x'
}
buildtools=

fetch_or_checkout_source

export CDPATH=

check_buildtools
clone_source_to_build

# Rebuild.
(
	cd build
	export CFLAGS=-O2
	sh Build.sh -r
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual

# ##############################################################################
# Build all of the ...{new} files in ./command and ./manual.
install_commands_0 .
install_manuals_0 mans ''
collapse_utf8_man_0

# ##############################################################################
# Rename the ...{new} files in ./command and ./manual.
install_commands_1
install_manuals_1 ''
collapse_utf8_man_1
