#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

name='zsh'
version='5.9.2'
gittag="v${version}"
source_archive() {
	extension='.tar.xz'
	url='ftp://ftp.'"${name}"'.org/pub/'"${name}"'-'"${version}${extension}"
	SHA256='36fa734374b44783582cec09bcd67822e2f992c779ec1624ab5596df078d2f81'
	SIZE='3439480'
}
buildtools=

apply_local_changes() {
	ln -f -s -- . source/Doc/man1
	mv -- source/Doc/zshall.1 source/Doc/zshall.1.orig
	soelim -I source/Doc source/Doc/zshall.1.orig > source/Doc/zshall.1
}

fetch_or_checkout_source

export CDPATH=

uses_gnu_make
check_buildtools
clone_source_to_build

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
target="${PWD}"
case "`uname`" in
Linux)
	pkgbase='/usr'
	shrbase="${pkgbase}"/share/"${name}"
	etcdir="${pkgbase}"/../etc/"${name}"
	;;
FreeBSD)
	pkgbase='/usr/local'
	shrbase="${pkgbase}"/share/"${name}"
	etcdir="${pkgbase}"/etc/"${name}"
	;;
*)
	pkgbase='/usr/pkg'
	shrbase="${pkgbase}"/share/"${name}"
	etcdir="${pkgbase}"/etc/"${name}"
	;;
esac
(
	cd build
	test -r config.status || sh ./configure --prefix="${target}" --build="$(slashpackage_target)" --libdir="${target}"/library --mandir="${target}"/manual --bindir="${target}"/command --enable-etcdir="${target}"/config/startup --enable-fndir="${target}"/config/functions --enable-site-fndir="${target}"/config/site-functions --enable-scriptdir="${target}"/config/scripts --enable-site-scriptdir="${target}"/config/site-scripts --enable-runhelpdir="${target}"/config/help --enable-maildir-support --enable-multibyte --enable-year2038 --enable-function-subdirs --enable-unicode9 --enable-cppflags='-isystem /usr/pkg/include' --enable-ldflags='-L /usr/pkg/lib'
	"${make}" ${cpus:+ -j "${cpus}"}
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual library library/param library/net config config/scripts config/functions config/help

# ##############################################################################
# Build all of the ...{new} files in ./command, ./config, ./manual, and ./library.
install_commands_0 Src
install_manuals_0 Doc ''
collapse_utf8_man_0
# All of the shared libraries
test -r package/shared_libraries && cat package/shared_libraries |
while read -r src dest
do
	if > /dev/null expr "${dest}" : 'curses.so' && ! test -r build/Src/"${src}"
	then
		continue
	fi
	rm -f -- library/"${dest}"{new}
	install -m 0755 -p -- build/Src/"${src}" library/"${dest}"{new}
	strip -p -- library/"${dest}"{new}
	chmod 0555 library/"${dest}"{new}
done
# Symbolic links in place of subdirectories to fool the dynamic linking
for directory in "${name}" "${version}"
do
	make_symbolic_link . library/"${directory}"{new}
done
# All of the scripts
for script in build/Scripts/*
do
	dest=scripts/$(basename "${script}")
	rm -f -- config/"${dest}"{new}
	install -m 0755 -p -- "${script}" config/"${dest}"{new}
done
# All of the functions
find build/Functions/ -type d |
while read -r fndir
do
	destdir=functions/"${fndir##build/Functions/}"
	install -d -m 0755 config/"${destdir}"
done
find build/Functions/ -type f \! -name '.*' |
while read -r fn
do
	dest=functions/"${fn##build/Functions/}"
	rm -f -- config/"${dest}"{new}
	install -m 0644 -p -- "${fn}" config/"${dest}"{new}
done
sed -i -e 's:@runhelpdir@:'"${target}"'/config/help:' config/functions/Misc/run-help{new}
find build/Completion/ -maxdepth 1 -type d |
while read -r fndir
do
	destdir=functions/"${fndir##build/}"
	install -d -m 0755 config/"${destdir}"
done
find build/Completion -type f \! -name '.*' |
while read -r fn
do
	# The multiple-level source tree needs to be flattened to 1 sub-level.
	rawname="${fn#build/Completion/}"
	dirname="$(dirname "${rawname}")"
	dirname="${dirname%%/*}"
	dest=functions/Completion/"${dirname}"/"$(basename "${rawname}")"
	rm -f -- config/"${dest}"{new}
	install -m 0644 -p -- "${fn}" config/"${dest}"{new}
done
for dest in site-functions site-scripts
do
	rm -f -- config/"${dest}"{new}
	ln -f -s -- "${shrbase}"/"${dest}" config/"${dest}"{new}
done
for dest in startup
do
	rm -f -- config/"${dest}"{new}
	ln -f -s -- "${etcdir}" config/"${dest}"{new}
done
# All of the help
find build/Doc/help/ -type f \! -name '.*' |
while read -r fn
do
	dest="${fn##build/Doc/}"
	rm -f -- config/"${dest}"{new}
	install -m 0644 -p -- "${fn}" config/"${dest}"{new}
done

# ##############################################################################
# Rename the ...{new} files in ./command, ./config, ./manual, and ./library.
install_commands_1
install_manuals_1 '' ''
collapse_utf8_man_1
# All of the shared libraries
test -r package/shared_libraries && cat package/shared_libraries |
while read -r src dest
do
	if > /dev/null expr "${dest}" : 'curses.so' && ! test -r library/"${dest}"{new}
	then
		continue
	fi
	mv -f -- library/"${dest}"{new} library/"${dest}"
done
# Symbolic links in place of subdirectories to fool the dynamic linking
for directory in "${name}" "${version}"
do
	rename_symbolic_link library/"${directory}"{new} library/"${directory}"
done
# All of the scripts
for script in build/Scripts/*
do
	dest=scripts/$(basename "${script}")
	mv -f -- config/"${dest}"{new} config/"${dest}"
done
# All of the functions
find build/Functions/ -type f \! -name '.*' |
while read -r fn
do
	dest=functions/"${fn##build/Functions/}"
	mv -f -- config/"${dest}"{new} config/"${dest}"
done
find build/Completion/ -type f \! -name '.*' |
while read -r fn
do
	# The multiple-level source tree needs to be flattened to 1 sub-level.
	rawname="${fn#build/Completion/}"
	dirname="$(dirname "${rawname}")"
	dirname="${dirname%%/*}"
	dest=functions/Completion/"${dirname}"/"$(basename "${rawname}")"
	mv -f -- config/"${dest}"{new} config/"${dest}"
done
for dest in site-functions site-scripts startup
do
	case "`uname`" in
	Linux)
		test -e config/"${dest}" && mv -f -- config/"${dest}" config/"${dest}"{old}
		mv -f -- config/"${dest}"{new} config/"${dest}"
		rm -f -- config/"${dest}"{old}
		;;
	*)
		mv -f -h -- config/"${dest}"{new} config/"${dest}"
		;;
	esac
done
# All of the help
find build/Doc/help/ -type f \! -name '.*' |
while read -r fn
do
	dest="${fn##build/Doc/}"
	mv -f -- config/"${dest}"{new} config/"${dest}"
done

# ##############################################################################
# Generate .zwc files as an optimization.
find config/functions config/functions/Completion -mindepth 1 -maxdepth 2 -type d |
while read -r dir
do
	build/Src/zsh -df -c 'zcompile -U -M "'"${dir}"'"{new}.zwc '"$(find "${dir}" -type f \! \( -name '.*' -o -name 'README*' -o -name '*.zwc' \)|tr '\n' ' ')"
	mv -f -- "${dir}"'{new}'.zwc "${dir}"'.zwc'
done
