#!/bin/sh -e
# See http://jdebp.uk./FGA/slashpackage.html
if test \! -d package
then
	echo "You are not in the right directory." 1>&2
	exit 100
fi

. ../../package_scripts.subr	# Use common slashpackage shell function library.

buildtools=

apply_local_changes() {
	local file
	if test -d package/patches
	then
		find package/patches -name '*.1' |
		while read -r file
		do
			test -r source/"$(basename "${file}")" || cp -p -- "${file}" source/
		done
	fi
}

# Create and checkout the source directory.
if test \! -d source
then
	install -d -m 0755 source
	source="${PWD}"/source
	if test -d /usr/src/bin/pax
	then
		( cd /usr/src/bin/pax && (2>/dev/null pax -w -r -l -u -- * "${source}" || true ) )
		apply_local_modifications
	else
		echo "/usr/src/bin/pax does not exist." 1>&2
		exit 100
	fi
fi

export CDPATH=

uses_bsd_make
check_buildtools
clone_source_to_build

# Rebuild.
if ! > /dev/null expr "${MAKEFLAGS}" : "--jobs" &&
   ! > /dev/null expr "${REDOFLAGS}" : "--jobs"
then
	calculate_make_cpus
fi
(
	cd build
	"${make}" ${cpus:+ -j "${cpus}"}
)

# Atomically update the release directories ./command, ./library, ./include, and so forth.
# The build and release directories need not be on the same disc volume.
# And the files released must not be potentially overwritable and truncatable by the compiler/linker during subsequent builds.
# But released files can be links to other released files, of course.
install -d -m 0755 command manual

# ##############################################################################
# Build all of the ...{new} files in ./command and ./manual.
install_commands_0 .
install_manuals_0 . ''
collapse_utf8_man_0

# ##############################################################################
# Rename the ...{new} files in ./command and ./manual.
install_commands_1
install_manuals_1 ''
collapse_utf8_man_1
